/**
 * Comprehensive 50-State Compliance Rules Seeder
 *
 * This script populates Firestore with labor law compliance rules for all 50 US states.
 * Rules are based on current state and federal labor laws as of 2024.
 *
 * Run from ChronoWorks directory: node scripts/seed_compliance_rules.js
 */

const admin = require('firebase-admin');
const serviceAccount = require('../functions/serviceAccountKey.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

// Current version - increment when updating rules
const RULES_VERSION = '2024.1.0';
const RULES_EFFECTIVE_DATE = new Date('2024-01-01');

/**
 * Generate all compliance rules for all 50 states
 */
function generateAllRules() {
  const now = admin.firestore.Timestamp.now();
  const rules = [];

  // ============================================================
  // FEDERAL RULES (Apply to all states)
  // ============================================================

  rules.push({
    id: 'fed_weekly_ot',
    name: 'Federal Weekly Overtime',
    description: 'Non-exempt employees must receive 1.5x pay for hours over 40 per week',
    category: 'weeklyOvertime',
    jurisdiction: 'federal',
    state: null,
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('1938-10-24')),
    expirationDate: null,
    legalReference: 'FLSA Section 7(a)',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'fed_minor_hours',
    name: 'Federal Minor Work Hours',
    description: 'Minors 14-15: max 3 hours on school days, 8 hours non-school days, 18 hours school weeks, 40 hours non-school weeks',
    category: 'minorHours',
    jurisdiction: 'federal',
    state: null,
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: 3,
    maxHoursNonSchoolDay: 8,
    maxConsecutiveDays: null,
    enforcementAction: 'blockAction',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('1938-10-24')),
    expirationDate: null,
    legalReference: 'FLSA Child Labor Provisions 29 CFR 570',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'fed_minor_timing',
    name: 'Federal Minor Work Timing',
    description: 'Minors 14-15 may only work between 7am-7pm (extended to 9pm June 1 through Labor Day)',
    category: 'minorTiming',
    jurisdiction: 'federal',
    state: null,
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: '07:00-19:00',
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'blockAction',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('1938-10-24')),
    expirationDate: null,
    legalReference: 'FLSA Child Labor Provisions 29 CFR 570',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // ALABAMA - Federal only (no state-specific requirements)
  // ============================================================
  rules.push({
    id: 'al_info',
    name: 'Alabama - Federal Standards Apply',
    description: 'Alabama has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'AL',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Alabama follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // ALASKA
  // ============================================================
  rules.push({
    id: 'ak_daily_ot',
    name: 'Alaska Daily Overtime',
    description: 'Employees must receive 1.5x pay for hours over 8 per day',
    category: 'dailyOvertime',
    jurisdiction: 'state',
    state: 'AK',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 8,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Alaska Statute 23.10.060',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ak_meal_break',
    name: 'Alaska Meal Break',
    description: 'Employees under 18 must receive a 30-minute meal break if working 6+ consecutive hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'AK',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: 'Applies to minors only',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Alaska Statute 23.10.350',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // ARIZONA - Federal only
  // ============================================================
  rules.push({
    id: 'az_info',
    name: 'Arizona - Federal Standards Apply',
    description: 'Arizona has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'AZ',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Arizona follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // ARKANSAS
  // ============================================================
  rules.push({
    id: 'ar_info',
    name: 'Arkansas - Federal Standards Apply',
    description: 'Arkansas has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'AR',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Arkansas follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // CALIFORNIA (Comprehensive)
  // ============================================================
  rules.push({
    id: 'ca_meal_break',
    name: 'California Meal Break',
    description: 'Employees must receive a 30-minute unpaid meal break no later than the end of the 5th hour of work',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'CA',
    city: null,
    industries: null,
    hoursThreshold: 5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Written waiver if shift is 6 hours or less',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'California Labor Code Section 512',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ca_second_meal',
    name: 'California Second Meal Break',
    description: 'Employees working over 10 hours must receive a second 30-minute meal break',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'CA',
    city: null,
    industries: null,
    hoursThreshold: 10,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Can waive if first meal break was not waived and shift is 12 hours or less',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'California Labor Code Section 512',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ca_rest_break',
    name: 'California Rest Break',
    description: 'Employees must receive a paid 10-minute rest break for every 4 hours worked (or major fraction thereof)',
    category: 'restBreak',
    jurisdiction: 'state',
    state: 'CA',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 10,
    warningMinutesBefore: 15,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'California Labor Code Section 226.7, IWC Wage Orders',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ca_daily_ot',
    name: 'California Daily Overtime',
    description: 'Non-exempt employees must receive 1.5x pay for hours over 8 per day',
    category: 'dailyOvertime',
    jurisdiction: 'state',
    state: 'CA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 8,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'California Labor Code Section 510',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ca_double_time',
    name: 'California Double Time',
    description: 'Employees must receive 2x pay for hours over 12 per day',
    category: 'doubleTime',
    jurisdiction: 'state',
    state: 'CA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 30,
    overtimeThreshold: 12,
    overtimeMultiplier: 2.0,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'California Labor Code Section 510',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ca_7th_day',
    name: 'California 7th Consecutive Day',
    description: 'Employees working 7 consecutive days in a workweek receive 1.5x for first 8 hours, 2x after 8 hours',
    category: 'consecutiveDays',
    jurisdiction: 'state',
    state: 'CA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: 6,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'California Labor Code Section 510',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // COLORADO
  // ============================================================
  rules.push({
    id: 'co_meal_break',
    name: 'Colorado Meal Break',
    description: 'Employees must receive a 30-minute uninterrupted meal break when working 5+ consecutive hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'CO',
    city: null,
    industries: null,
    hoursThreshold: 5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Employee must be completely relieved of duties',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Colorado COMPS Order #38, 7 CCR 1103-1',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'co_rest_break',
    name: 'Colorado Rest Break',
    description: 'Employees must receive a paid 10-minute rest break for every 4 hours worked',
    category: 'restBreak',
    jurisdiction: 'state',
    state: 'CO',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 10,
    warningMinutesBefore: 15,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Colorado COMPS Order #38, 7 CCR 1103-1',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'co_daily_ot',
    name: 'Colorado Daily Overtime',
    description: 'Employees must receive 1.5x pay for hours over 12 per day or 12 consecutive hours',
    category: 'dailyOvertime',
    jurisdiction: 'state',
    state: 'CO',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 12,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Colorado COMPS Order #38',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // CONNECTICUT
  // ============================================================
  rules.push({
    id: 'ct_meal_break',
    name: 'Connecticut Meal Break',
    description: 'Employees must receive a 30-minute meal break after first 2 hours and before last 2 hours of shifts 7.5+ hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'CT',
    city: null,
    industries: null,
    hoursThreshold: 7.5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Written agreement between employer and employee',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Connecticut General Statutes Section 31-51ii',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // DELAWARE
  // ============================================================
  rules.push({
    id: 'de_meal_break',
    name: 'Delaware Meal Break',
    description: 'Employees must receive a 30-minute meal break after first 2 hours and before last 2 hours for shifts 7.5+ hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'DE',
    city: null,
    industries: null,
    hoursThreshold: 7.5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Delaware Code Title 19, Section 707',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // FLORIDA - Federal only
  // ============================================================
  rules.push({
    id: 'fl_info',
    name: 'Florida - Federal Standards Apply',
    description: 'Florida has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors under 18 require 30-minute break for 4+ hour shifts.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'FL',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Florida Statute 450.081 (minors only)',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'fl_minor_break',
    name: 'Florida Minor Meal Break',
    description: 'Employees under 18 must receive a 30-minute uninterrupted break for every 4 hours of continuous work',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'FL',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: 'Applies to minors only',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Florida Statute 450.081',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // GEORGIA - Federal only
  // ============================================================
  rules.push({
    id: 'ga_info',
    name: 'Georgia - Federal Standards Apply',
    description: 'Georgia has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'GA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Georgia follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // HAWAII
  // ============================================================
  rules.push({
    id: 'hi_info',
    name: 'Hawaii - Federal Standards Apply',
    description: 'Hawaii has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors 14-15 require breaks.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'HI',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Hawaii follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // IDAHO - Federal only
  // ============================================================
  rules.push({
    id: 'id_info',
    name: 'Idaho - Federal Standards Apply',
    description: 'Idaho has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'ID',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Idaho follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // ILLINOIS
  // ============================================================
  rules.push({
    id: 'il_meal_break',
    name: 'Illinois Meal Break',
    description: 'Employees must receive a 20-minute meal break no later than 5 hours after starting work for shifts 7.5+ hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'IL',
    city: null,
    industries: null,
    hoursThreshold: 7.5,
    durationMinutes: 20,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Illinois One Day Rest in Seven Act, 820 ILCS 140',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'il_one_day_rest',
    name: 'Illinois One Day Rest in Seven',
    description: 'Employees must receive at least 24 consecutive hours of rest in every calendar week',
    category: 'consecutiveDays',
    jurisdiction: 'state',
    state: 'IL',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: 6,
    enforcementAction: 'warnManager',
    isWaivable: true,
    waiverRequirements: 'Voluntary written request from employee',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Illinois One Day Rest in Seven Act, 820 ILCS 140',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // INDIANA - Federal only
  // ============================================================
  rules.push({
    id: 'in_info',
    name: 'Indiana - Federal Standards Apply',
    description: 'Indiana has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'IN',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Indiana follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // IOWA - Federal only
  // ============================================================
  rules.push({
    id: 'ia_info',
    name: 'Iowa - Federal Standards Apply',
    description: 'Iowa has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'IA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Iowa follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // KANSAS - Federal only
  // ============================================================
  rules.push({
    id: 'ks_info',
    name: 'Kansas - Federal Standards Apply',
    description: 'Kansas has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'KS',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Kansas follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // KENTUCKY
  // ============================================================
  rules.push({
    id: 'ky_meal_break',
    name: 'Kentucky Meal Break',
    description: 'Employees must receive a reasonable meal break (typically 30 minutes) close to the middle of the scheduled work period',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'KY',
    city: null,
    industries: null,
    hoursThreshold: 5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Kentucky Revised Statutes 337.355',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ky_rest_break',
    name: 'Kentucky Rest Break',
    description: 'Employees must receive a paid 10-minute rest break for every 4 hours worked',
    category: 'restBreak',
    jurisdiction: 'state',
    state: 'KY',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 10,
    warningMinutesBefore: 15,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Kentucky Revised Statutes 337.365',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // LOUISIANA - Federal only
  // ============================================================
  rules.push({
    id: 'la_info',
    name: 'Louisiana - Federal Standards Apply',
    description: 'Louisiana has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors under 18 have specific requirements.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'LA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Louisiana follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MAINE
  // ============================================================
  rules.push({
    id: 'me_meal_break',
    name: 'Maine Meal Break',
    description: 'Employees must receive a 30-minute unpaid rest break after 6 consecutive hours of work',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'ME',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Maine Revised Statutes Title 26, Section 601',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MARYLAND
  // ============================================================
  rules.push({
    id: 'md_retail_break',
    name: 'Maryland Retail Break',
    description: 'Retail employees must receive a 15-minute break for 4-6 hour shifts, or 30-minute break for 6+ hour shifts',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'MD',
    city: null,
    industries: ['Retail'],
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Written agreement between employer and employee',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Maryland Labor and Employment Code Section 3-710',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MASSACHUSETTS
  // ============================================================
  rules.push({
    id: 'ma_meal_break',
    name: 'Massachusetts Meal Break',
    description: 'Employees must receive a 30-minute meal break for shifts over 6 hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'MA',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Attorney General approval required for waiver',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Massachusetts General Laws Chapter 149, Section 100',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MICHIGAN - Federal only
  // ============================================================
  rules.push({
    id: 'mi_info',
    name: 'Michigan - Federal Standards Apply',
    description: 'Michigan has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors have specific requirements.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'MI',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Michigan follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MINNESOTA
  // ============================================================
  rules.push({
    id: 'mn_meal_break',
    name: 'Minnesota Meal Break',
    description: 'Employees must receive sufficient time to eat a meal for shifts 8+ hours. Typically interpreted as 30 minutes.',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'MN',
    city: null,
    industries: null,
    hoursThreshold: 8,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Minnesota Statutes Section 177.254',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'mn_restroom_break',
    name: 'Minnesota Restroom Break',
    description: 'Employees must have adequate time within each 4 consecutive hours of work to use the restroom',
    category: 'restBreak',
    jurisdiction: 'state',
    state: 'MN',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 10,
    warningMinutesBefore: 15,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Minnesota Statutes Section 177.253',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MISSISSIPPI - Federal only
  // ============================================================
  rules.push({
    id: 'ms_info',
    name: 'Mississippi - Federal Standards Apply',
    description: 'Mississippi has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'MS',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Mississippi follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MISSOURI - Federal only
  // ============================================================
  rules.push({
    id: 'mo_info',
    name: 'Missouri - Federal Standards Apply',
    description: 'Missouri has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'MO',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Missouri follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // MONTANA - Federal only
  // ============================================================
  rules.push({
    id: 'mt_info',
    name: 'Montana - Federal Standards Apply',
    description: 'Montana has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'MT',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Montana follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NEBRASKA
  // ============================================================
  rules.push({
    id: 'ne_meal_break',
    name: 'Nebraska Meal Break (Assembly Plants)',
    description: 'Employees in assembly plant, mechanical, or workshop establishments must receive a 30-minute lunch break in each 8-hour shift',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'NE',
    city: null,
    industries: ['Manufacturing', 'Assembly'],
    hoursThreshold: 8,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Nebraska Revised Statutes 48-212',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NEVADA
  // ============================================================
  rules.push({
    id: 'nv_meal_break',
    name: 'Nevada Meal Break',
    description: 'Employees must receive a 30-minute meal break when working 8+ continuous hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'NV',
    city: null,
    industries: null,
    hoursThreshold: 8,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Mutual agreement if nature of work allows eating during work',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Nevada Revised Statutes 608.019',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'nv_rest_break',
    name: 'Nevada Rest Break',
    description: 'Employees must receive a paid 10-minute rest break for every 4 hours worked',
    category: 'restBreak',
    jurisdiction: 'state',
    state: 'NV',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 10,
    warningMinutesBefore: 15,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Nevada Revised Statutes 608.019',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'nv_daily_ot',
    name: 'Nevada Daily Overtime',
    description: 'Employees must receive 1.5x pay for hours over 8 per day (unless earning 1.5x minimum wage)',
    category: 'dailyOvertime',
    jurisdiction: 'state',
    state: 'NV',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 8,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Nevada Constitution Article 15, Section 16',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NEW HAMPSHIRE
  // ============================================================
  rules.push({
    id: 'nh_meal_break',
    name: 'New Hampshire Meal Break',
    description: 'Employees must receive a 30-minute meal break after 5 consecutive hours of work',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'NH',
    city: null,
    industries: null,
    hoursThreshold: 5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'If employee is allowed to eat while working and nature of work permits',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'New Hampshire RSA 275:30-a',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NEW JERSEY - Federal only (but has strong enforcement)
  // ============================================================
  rules.push({
    id: 'nj_info',
    name: 'New Jersey - Federal Standards Apply',
    description: 'New Jersey has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors under 18 require 30-minute break.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'NJ',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'New Jersey follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NEW MEXICO - Federal only
  // ============================================================
  rules.push({
    id: 'nm_info',
    name: 'New Mexico - Federal Standards Apply',
    description: 'New Mexico has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'NM',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'New Mexico follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NEW YORK
  // ============================================================
  rules.push({
    id: 'ny_meal_break',
    name: 'New York Meal Break (Noon)',
    description: 'Employees must receive a 30-minute meal break between 11am and 2pm for shifts starting before 11am and continuing past 2pm',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'NY',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'New York Labor Law Section 162',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ny_meal_break_evening',
    name: 'New York Meal Break (Evening)',
    description: 'Factory employees must receive a 60-minute meal break between 5pm and 7pm when shift extends past 7pm',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'NY',
    city: null,
    industries: ['Manufacturing'],
    hoursThreshold: 6,
    durationMinutes: 60,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'New York Labor Law Section 162',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ny_spread_of_hours',
    name: 'New York Spread of Hours',
    description: 'Employees whose workday spans more than 10 hours are entitled to an extra hour at minimum wage',
    category: 'splitShift',
    jurisdiction: 'state',
    state: 'NY',
    city: null,
    industries: null,
    hoursThreshold: 10,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'New York Labor Law, 12 NYCRR 142-2.4',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'ny_one_day_rest',
    name: 'New York Day of Rest',
    description: 'Employees in certain industries must receive at least 24 consecutive hours of rest in each calendar week',
    category: 'consecutiveDays',
    jurisdiction: 'state',
    state: 'NY',
    city: null,
    industries: ['Manufacturing', 'Retail', 'Hospitality'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: 6,
    enforcementAction: 'warnManager',
    isWaivable: true,
    waiverRequirements: 'Written voluntary request from employee',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'New York Labor Law Section 161',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NORTH CAROLINA - Federal only
  // ============================================================
  rules.push({
    id: 'nc_info',
    name: 'North Carolina - Federal Standards Apply',
    description: 'North Carolina has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors under 16 require 30-minute break.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'NC',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'North Carolina follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // NORTH DAKOTA
  // ============================================================
  rules.push({
    id: 'nd_meal_break',
    name: 'North Dakota Meal Break',
    description: 'Employees must receive a 30-minute meal break when working 5+ consecutive hours, unless fewer than 2 employees on duty',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'ND',
    city: null,
    industries: null,
    hoursThreshold: 5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'If fewer than 2 employees on duty',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'North Dakota Admin Code 46-02-07-02',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // OHIO - Federal only
  // ============================================================
  rules.push({
    id: 'oh_info',
    name: 'Ohio - Federal Standards Apply',
    description: 'Ohio has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors have specific requirements.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'OH',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Ohio follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // OKLAHOMA - Federal only
  // ============================================================
  rules.push({
    id: 'ok_info',
    name: 'Oklahoma - Federal Standards Apply',
    description: 'Oklahoma has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'OK',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Oklahoma follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // OREGON
  // ============================================================
  rules.push({
    id: 'or_meal_break',
    name: 'Oregon Meal Break',
    description: 'Employees must receive a 30-minute unpaid meal break for shifts 6+ hours, taken between hours 2 and 5',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'OR',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'Mutual agreement if 6 hours or less shift',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Oregon ORS 653.261, OAR 839-020-0050',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'or_rest_break',
    name: 'Oregon Rest Break',
    description: 'Employees must receive a paid 10-minute rest break for every 4 hours worked (or major fraction)',
    category: 'restBreak',
    jurisdiction: 'state',
    state: 'OR',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 10,
    warningMinutesBefore: 15,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Oregon ORS 653.261, OAR 839-020-0050',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'or_predictive_scheduling',
    name: 'Oregon Predictive Scheduling',
    description: 'Retail, food service, and hospitality employers with 500+ employees must provide schedules 14 days in advance',
    category: 'predictiveScheduling',
    jurisdiction: 'state',
    state: 'OR',
    city: null,
    industries: ['Retail', 'Restaurant / Food Service', 'Hospitality'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: 14,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('2018-07-01')),
    expirationDate: null,
    legalReference: 'Oregon SB 828',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // PENNSYLVANIA - Federal only
  // ============================================================
  rules.push({
    id: 'pa_info',
    name: 'Pennsylvania - Federal Standards Apply',
    description: 'Pennsylvania has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors under 18 require 30-minute break for 5+ hour shifts.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'PA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Pennsylvania follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // RHODE ISLAND
  // ============================================================
  rules.push({
    id: 'ri_meal_break',
    name: 'Rhode Island Meal Break',
    description: 'Employees must receive a 20-minute meal break within 6 hours of starting work, for shifts 8+ hours',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'RI',
    city: null,
    industries: null,
    hoursThreshold: 8,
    durationMinutes: 20,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Rhode Island General Laws Section 28-3-14',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // SOUTH CAROLINA - Federal only
  // ============================================================
  rules.push({
    id: 'sc_info',
    name: 'South Carolina - Federal Standards Apply',
    description: 'South Carolina has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'SC',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'South Carolina follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // SOUTH DAKOTA - Federal only
  // ============================================================
  rules.push({
    id: 'sd_info',
    name: 'South Dakota - Federal Standards Apply',
    description: 'South Dakota has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'SD',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'South Dakota follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // TENNESSEE
  // ============================================================
  rules.push({
    id: 'tn_meal_break',
    name: 'Tennessee Meal Break',
    description: 'Employees scheduled to work 6+ consecutive hours must receive a 30-minute unpaid meal break',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'TN',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Tennessee Code Annotated Section 50-2-103',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // TEXAS - Federal only
  // ============================================================
  rules.push({
    id: 'tx_info',
    name: 'Texas - Federal Standards Apply',
    description: 'Texas has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'TX',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Texas follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // UTAH - Federal only
  // ============================================================
  rules.push({
    id: 'ut_info',
    name: 'Utah - Federal Standards Apply',
    description: 'Utah has no state meal or rest break requirements for adult employees. Federal FLSA standards apply. Minors under 18 require 30-minute break for 5+ hour shifts.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'UT',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Utah follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // VERMONT
  // ============================================================
  rules.push({
    id: 'vt_meal_break',
    name: 'Vermont Break Requirement',
    description: 'Employees must be given reasonable opportunities during work periods to eat and use toilet facilities',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'VT',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Vermont Statutes Title 21, Section 304',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // VIRGINIA - Federal only
  // ============================================================
  rules.push({
    id: 'va_info',
    name: 'Virginia - Federal Standards Apply',
    description: 'Virginia has no state meal or rest break requirements for adult employees. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'VA',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Virginia follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // WASHINGTON
  // ============================================================
  rules.push({
    id: 'wa_meal_break',
    name: 'Washington Meal Break',
    description: 'Employees must receive a 30-minute meal break when working more than 5 consecutive hours, no later than end of 5th hour',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'WA',
    city: null,
    industries: null,
    hoursThreshold: 5,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: true,
    waiverRequirements: 'If employee will be relieved of all duties and shift is 6 hours or less',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Washington WAC 296-126-092',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'wa_rest_break',
    name: 'Washington Rest Break',
    description: 'Employees must receive a paid 10-minute rest break for every 4 hours worked, scheduled as near to midpoint as possible',
    category: 'restBreak',
    jurisdiction: 'state',
    state: 'WA',
    city: null,
    industries: null,
    hoursThreshold: 4,
    durationMinutes: 10,
    warningMinutesBefore: 15,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Washington WAC 296-126-092',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // WEST VIRGINIA
  // ============================================================
  rules.push({
    id: 'wv_meal_break',
    name: 'West Virginia Meal Break',
    description: 'Employees must receive a 20-minute meal break for shifts 6+ hours (not more than 5 hours after beginning work)',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'WV',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 20,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnEmployee',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'West Virginia Code Section 21-3-10a',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // WISCONSIN
  // ============================================================
  rules.push({
    id: 'wi_meal_break',
    name: 'Wisconsin Meal Break Recommendation',
    description: 'Wisconsin recommends (but does not require) a 30-minute meal break for shifts 6+ hours. Minors require 30-minute break for 6+ hour shifts.',
    category: 'mealBreak',
    jurisdiction: 'state',
    state: 'WI',
    city: null,
    industries: null,
    hoursThreshold: 6,
    durationMinutes: 30,
    warningMinutesBefore: 30,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'notify',
    isWaivable: true,
    waiverRequirements: 'Recommended but not required for adults',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Wisconsin Admin Code DWD 274.02',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  rules.push({
    id: 'wi_one_day_rest',
    name: 'Wisconsin Day of Rest',
    description: 'Factory and retail employees must receive at least 24 consecutive hours of rest in each calendar week',
    category: 'consecutiveDays',
    jurisdiction: 'state',
    state: 'WI',
    city: null,
    industries: ['Manufacturing', 'Retail'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: 6,
    enforcementAction: 'warnManager',
    isWaivable: true,
    waiverRequirements: 'Employee can voluntarily agree to work all 7 days',
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Wisconsin Statutes Section 103.85',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // WYOMING - Federal only
  // ============================================================
  rules.push({
    id: 'wy_info',
    name: 'Wyoming - Federal Standards Apply',
    description: 'Wyoming has no state meal or rest break requirements. Federal FLSA standards apply.',
    category: 'weeklyOvertime',
    jurisdiction: 'state',
    state: 'WY',
    city: null,
    industries: null,
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 60,
    overtimeThreshold: 40,
    overtimeMultiplier: 1.5,
    advanceNoticeDays: null,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(RULES_EFFECTIVE_DATE),
    expirationDate: null,
    legalReference: 'Wyoming follows federal FLSA',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // ============================================================
  // CITY-SPECIFIC RULES
  // ============================================================

  // Seattle Secure Scheduling
  rules.push({
    id: 'seattle_secure_scheduling',
    name: 'Seattle Secure Scheduling',
    description: 'Retail and food service employers with 500+ employees worldwide must provide schedules 14 days in advance',
    category: 'predictiveScheduling',
    jurisdiction: 'city',
    state: 'WA',
    city: 'Seattle',
    industries: ['Retail', 'Restaurant / Food Service'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: 14,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('2017-07-01')),
    expirationDate: null,
    legalReference: 'Seattle Municipal Code 14.22',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // NYC Fast Food Scheduling
  rules.push({
    id: 'nyc_fast_food_scheduling',
    name: 'NYC Fast Food Scheduling',
    description: 'Fast food employers in NYC must provide schedules 14 days in advance. Premium pay for schedule changes.',
    category: 'predictiveScheduling',
    jurisdiction: 'city',
    state: 'NY',
    city: 'New York City',
    industries: ['Restaurant / Food Service'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: 14,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('2017-11-26')),
    expirationDate: null,
    legalReference: 'NYC Admin Code 20-1221',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // San Francisco Retail Workers Bill of Rights
  rules.push({
    id: 'sf_retail_scheduling',
    name: 'San Francisco Retail Scheduling',
    description: 'Retail employers with 20+ employees in SF must provide schedules 14 days in advance',
    category: 'predictiveScheduling',
    jurisdiction: 'city',
    state: 'CA',
    city: 'San Francisco',
    industries: ['Retail'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: 14,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('2015-01-01')),
    expirationDate: null,
    legalReference: 'San Francisco Police Code Article 33F',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // Chicago Fair Workweek
  rules.push({
    id: 'chicago_fair_workweek',
    name: 'Chicago Fair Workweek',
    description: 'Covered employers must provide schedules 14 days in advance for hourly workers',
    category: 'predictiveScheduling',
    jurisdiction: 'city',
    state: 'IL',
    city: 'Chicago',
    industries: ['Retail', 'Restaurant / Food Service', 'Hospitality', 'Healthcare', 'Manufacturing', 'Warehouse'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: 14,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('2020-07-01')),
    expirationDate: null,
    legalReference: 'Chicago Municipal Code 1-25',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // Los Angeles Fair Workweek
  rules.push({
    id: 'la_fair_workweek',
    name: 'Los Angeles Fair Workweek',
    description: 'Retail employers with 300+ employees globally must provide schedules 14 days in advance',
    category: 'predictiveScheduling',
    jurisdiction: 'city',
    state: 'CA',
    city: 'Los Angeles',
    industries: ['Retail'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: 14,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('2023-04-01')),
    expirationDate: null,
    legalReference: 'Los Angeles Municipal Code Chapter XVIII Article 9',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  // Philadelphia Fair Workweek
  rules.push({
    id: 'philly_fair_workweek',
    name: 'Philadelphia Fair Workweek',
    description: 'Retail, hospitality, and food service employers with 250+ employees must provide schedules 14 days in advance',
    category: 'predictiveScheduling',
    jurisdiction: 'city',
    state: 'PA',
    city: 'Philadelphia',
    industries: ['Retail', 'Restaurant / Food Service', 'Hospitality'],
    hoursThreshold: null,
    durationMinutes: null,
    warningMinutesBefore: 0,
    overtimeThreshold: null,
    overtimeMultiplier: null,
    advanceNoticeDays: 14,
    timeRestriction: null,
    maxHoursSchoolDay: null,
    maxHoursNonSchoolDay: null,
    maxConsecutiveDays: null,
    enforcementAction: 'warnManager',
    isWaivable: false,
    waiverRequirements: null,
    isActive: true,
    effectiveDate: admin.firestore.Timestamp.fromDate(new Date('2020-04-01')),
    expirationDate: null,
    legalReference: 'Philadelphia Code Chapter 9-4600',
    version: RULES_VERSION,
    createdAt: now,
    updatedAt: now,
  });

  return rules;
}

/**
 * Seed all rules to Firestore
 */
async function seedComplianceRules() {
  console.log('\n========================================');
  console.log('  ChronoWorks Compliance Rules Seeder');
  console.log('========================================\n');

  const rules = generateAllRules();
  console.log(`Generated ${rules.length} compliance rules\n`);

  // Save metadata
  const metadataRef = db.collection('complianceMetadata').doc('rulesInfo');
  await metadataRef.set({
    version: RULES_VERSION,
    lastUpdated: admin.firestore.Timestamp.now(),
    totalRules: rules.length,
    federalRules: rules.filter(r => r.jurisdiction === 'federal').length,
    stateRules: rules.filter(r => r.jurisdiction === 'state').length,
    cityRules: rules.filter(r => r.jurisdiction === 'city').length,
  });

  // Batch write rules (Firestore batch limit is 500)
  const batchSize = 400;
  let batchCount = 0;
  let batch = db.batch();
  let rulesInBatch = 0;

  for (const rule of rules) {
    const docRef = db.collection('complianceRules').doc(rule.id);
    batch.set(docRef, rule, { merge: true });
    rulesInBatch++;

    if (rulesInBatch >= batchSize) {
      await batch.commit();
      batchCount++;
      console.log(`  Committed batch ${batchCount} (${rulesInBatch} rules)`);
      batch = db.batch();
      rulesInBatch = 0;
    }
  }

  // Commit remaining
  if (rulesInBatch > 0) {
    await batch.commit();
    batchCount++;
    console.log(`  Committed batch ${batchCount} (${rulesInBatch} rules)`);
  }

  console.log('\n========================================');
  console.log('  Seeding Complete!');
  console.log('========================================');
  console.log(`  Version: ${RULES_VERSION}`);
  console.log(`  Total Rules: ${rules.length}`);
  console.log(`  Federal: ${rules.filter(r => r.jurisdiction === 'federal').length}`);
  console.log(`  State: ${rules.filter(r => r.jurisdiction === 'state').length}`);
  console.log(`  City: ${rules.filter(r => r.jurisdiction === 'city').length}`);
  console.log('========================================\n');

  // List states with specific rules
  const statesWithRules = [...new Set(rules.filter(r => r.jurisdiction === 'state').map(r => r.state))];
  console.log('States with specific rules:');
  console.log(statesWithRules.sort().join(', '));
  console.log('\n');

  process.exit(0);
}

// Run the seeder
seedComplianceRules().catch(err => {
  console.error('Error seeding rules:', err);
  process.exit(1);
});
