// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpHt9zh1NJjangm2C4dGnh2dIjX1WdFWI',
    appId: '1:7115903467:web:3c0331d63df493539589ae',
    messagingSenderId: '7115903467',
    projectId: 'chronoworks-dcfd6',
    authDomain: 'chronoworks-dcfd6.firebaseapp.com',
    storageBucket: 'chronoworks-dcfd6.firebasestorage.app',
    measurementId: 'G-7K45X5MQHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGBDxJw9D2Nbix14jfD_hVFHJSQeY8LiY',
    appId: '1:7115903467:android:7dc70363a47bd3649589ae',
    messagingSenderId: '7115903467',
    projectId: 'chronoworks-dcfd6',
    storageBucket: 'chronoworks-dcfd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7H8rpxvFwlpq4XuXev3jEKSJzB7CdXhw',
    appId: '1:7115903467:ios:fd6a4d50e41e62579589ae',
    messagingSenderId: '7115903467',
    projectId: 'chronoworks-dcfd6',
    storageBucket: 'chronoworks-dcfd6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
}
